.TH vmarquee 1 "10 Nov 2016" "version 1.0" "V-MARQUEE"
.SH NAME
.B vmarquee
- my superb vertical marquee manipulator

.SH SYNOPSIS
vmarquee [-w]

.SH DESCRIPTION
This program is for manipulating "vertical text", you can enter new
text or use the default text. You should follow the instructions inside the
program instance. It is using curses to make the TUI (Text User Interface).

.SH OPTIONS
--waterfall, -w
.PP
Used for triggering waterfall mode, you will see lots of
text pouring down in all available columns at different speed if you turn on
this option

.SH BUGS
There are no bugs. Everything is features.

.SH AUTHORS
Chanchana Sornsoontorn <off9955555@gmail.com>

.SH SEE ALSO
curses(1)
